### ISSUE TITLE
如何调试参数？

### ISSUE THREAD

**Issue by xiangxiangjiang** [OneYoungMean/AutomaticDynamicBone#1]
您好，十分感谢您能分享布料模拟插件。我用你的插件尝试设置了一些头发和布料，但效果不是很理想，模型动作稍微大点，容易出现穿模和乱飞。不知您能否写一个简单的布料和头发和参数调试文档，简述一下头发和衣服的参数大概应该怎么分布。好做一个参考！再次感谢您的慷慨分享。

**Comment by OneYoungMean** [comment]
问题已计入Q&A大概今天晚点的时候就可以看到

**Comment by OneYoungMean** [comment]
https://github.com/OneYoungMean/AutomaticDynamicBone/wiki/%5B%E8%BF%9B%E9%98%B6%5DADBSetting%E4%BB%8B%E7%BB%8D#%E6%9C%89%E6%B2%A1%E6%9C%89%E6%AF%94%E8%BE%83%E9%80%82%E5%90%88%E4%BB%8E%E5%8F%82%E6%95%B0%E8%8C%83%E5%9B%B4%E7%9A%84%E5%BB%BA%E8%AE%AE

**Comment by xiangxiangjiang** [comment]
十分感谢！！！！
